
require 'mxx_ru/cpp/qt5'

Mxx_ru::Cpp::lib_target {

	rtl_mode( Mxx_ru::Cpp::RTL_SHARED )
	rtti_mode( Mxx_ru::Cpp::RTTI_ENABLED )
	threading_mode( Mxx_ru::Cpp::THREADING_MULTI )

    required_prj( 'Como/prj.rb' )
    required_prj( 'QtConfFile/prj.rb' )

	target( 'lib/Globe.Core' )
	
	qt = generator( MxxRu::Cpp::Qt5.new( self ) )
    qt.use_modules( QT_GUI, QT_NETWORK, QT_SQL, QT_WIDGETS, QT_MULTIMEDIA )
    
    if( MxxRu::Cpp::RUNTIME_DEBUG == mxx_runtime_mode )
        define( 'GLOBE_CORE_DEBUG' )
    end
    
    qt.ui( 'channel_attributes.ui' )
    qt.ui( 'channel_name_dialog.ui' )
    qt.ui( 'channels_to_show.ui' )
    qt.ui( 'configuration_dialog.ui' )
    qt.ui( 'log_event_selector.ui' )
    qt.ui( 'log_sources_selector.ui' )
    qt.ui( 'properties_cfg_filename_dialog.ui' )
    qt.ui( 'properties_dialog.ui' )
    qt.ui( 'properties_key_type_dialog.ui' )
    qt.ui( 'properties_mainwindow.ui' )
    qt.ui( 'select_query_navigation.ui' )
    qt.ui( 'sounds_disabled_to_dialog.ui' )
    qt.ui( 'source_manual_dialog.ui' )
    qt.ui( 'sources_widget.ui' )
    
    qt.qrc2cpp( 'resources.qrc' )
    
	qt.h2moc( 'channel_attributes.hpp' )
	qt.h2moc( 'channel_name_dialog.hpp' )
	qt.h2moc( 'channel_timeout_widget.hpp' )
	qt.h2moc( 'channel_view.hpp' )
	qt.h2moc( 'channel_view_window.hpp' )
	qt.h2moc( 'channel_view_window_model.hpp' )
	qt.h2moc( 'channel_widget.hpp' )
	qt.h2moc( 'channels.hpp' )
	qt.h2moc( 'channels_list.hpp' )
	qt.h2moc( 'channels_to_show.hpp' )
	qt.h2moc( 'color_for_level.hpp' )
	qt.h2moc( 'color_picker.hpp' )
	qt.h2moc( 'configuration.hpp' )
	qt.h2moc( 'configuration_dialog.hpp' )
	qt.h2moc( 'db.hpp' )
	qt.h2moc( 'log.hpp' )
	qt.h2moc( 'log_event_selector.hpp' )
	qt.h2moc( 'log_event_view.hpp' )
	qt.h2moc( 'log_event_view_model.hpp' )
	qt.h2moc( 'log_event_view_window.hpp' )
	qt.h2moc( 'log_sources_model.hpp' )
	qt.h2moc( 'log_sources_selector.hpp' )
	qt.h2moc( 'log_sources_view.hpp' )
	qt.h2moc( 'log_sources_window.hpp' )
	qt.h2moc( 'mainwindow.hpp' )
	qt.h2moc( 'properties_cfg_filename_dialog.hpp' )
	qt.h2moc( 'properties_dialog.hpp' )
	qt.h2moc( 'properties_key_type_dialog.hpp' )
	qt.h2moc( 'properties_manager.hpp' )
	qt.h2moc( 'properties_manager_view.hpp' )
	qt.h2moc( 'properties_model.hpp' )
	qt.h2moc( 'properties_widget.hpp' )
	qt.h2moc( 'properties_widget_model.hpp' )
	qt.h2moc( 'scrolled_widget.hpp' )
	qt.h2moc( 'select_query_navigation.hpp' )
	qt.h2moc( 'sounds.hpp' )
	qt.h2moc( 'sounds_disabled.hpp' )
	qt.h2moc( 'sounds_disabled_model.hpp' )
	qt.h2moc( 'sounds_disabled_to_dialog.hpp' )
	qt.h2moc( 'sounds_disabled_view.hpp' )
	qt.h2moc( 'sounds_played_model.hpp' )
	qt.h2moc( 'sounds_played_view.hpp' )
	qt.h2moc( 'source_manual_dialog.hpp' )
	qt.h2moc( 'sources.hpp' )
	qt.h2moc( 'sources_dialog.hpp' )
	qt.h2moc( 'sources_mainwindow.hpp' )
	qt.h2moc( 'sources_model.hpp' )
	qt.h2moc( 'sources_widget.hpp' )
	qt.h2moc( 'sources_widget_view.hpp' )
	qt.h2moc( 'tool_window_object.hpp' )
	
	qt.cpp2moc( 'channels.cpp' )
	qt.cpp2moc( 'properties_widget.cpp' )

	cpp_source( 'application_cfg.cpp' )
	cpp_source( 'channel_attributes.cpp' )
	cpp_source( 'channel_name_dialog.cpp' )
	cpp_source( 'channel_timeout_widget.cpp' )
	cpp_source( 'channel_view.cpp' )
	cpp_source( 'channel_view_window.cpp' )
	cpp_source( 'channel_view_window_cfg.cpp' )
	cpp_source( 'channel_view_window_model.cpp' )
	cpp_source( 'channel_widget.cpp' )
	cpp_source( 'channels.cpp' )
	cpp_source( 'channels_cfg.cpp' )
	cpp_source( 'channels_list.cpp' )
	cpp_source( 'channels_to_show.cpp' )
	cpp_source( 'color_for_level.cpp' )
	cpp_source( 'color_for_level_cfg.cpp' )
	cpp_source( 'color_picker.cpp' )
	cpp_source( 'condition.cpp' )
	cpp_source( 'condition_cfg.cpp' )
	cpp_source( 'configuration.cpp' )
	cpp_source( 'configuration_dialog.cpp' )
	cpp_source( 'db.cpp' )
	cpp_source( 'db_cfg.cpp' )
	cpp_source( 'globe_menu.cpp' )
	cpp_source( 'launch_time.cpp' )
	cpp_source( 'log.cpp' )
	cpp_source( 'log_cfg.cpp' )
	cpp_source( 'log_event_selector.cpp' )
	cpp_source( 'log_event_view.cpp' )
	cpp_source( 'log_event_view_model.cpp' )
	cpp_source( 'log_event_view_window.cpp' )
	cpp_source( 'log_event_view_window_cfg.cpp' )
	cpp_source( 'log_sources_model.cpp' )
	cpp_source( 'log_sources_selector.cpp' )
	cpp_source( 'log_sources_view.cpp' )
	cpp_source( 'log_sources_window.cpp' )
	cpp_source( 'log_sources_window_cfg.cpp' )
	cpp_source( 'mainwindow.cpp' )
	cpp_source( 'mainwindow_cfg.cpp' )
	cpp_source( 'properties.cpp' )
	cpp_source( 'properties_cfg.cpp' )
	cpp_source( 'properties_cfg_filename_dialog.cpp' )
	cpp_source( 'properties_dialog.cpp' )
	cpp_source( 'properties_key_type_dialog.cpp' )
	cpp_source( 'properties_manager.cpp' )
	cpp_source( 'properties_manager_view.cpp' )
	cpp_source( 'properties_map.cpp' )
	cpp_source( 'properties_model.cpp' )
	cpp_source( 'properties_widget.cpp' )
	cpp_source( 'properties_widget_model.cpp' )
	cpp_source( 'scrolled_widget.cpp' )
	cpp_source( 'select_query_navigation.cpp' )
	cpp_source( 'sounds.cpp' )
	cpp_source( 'sounds_cfg.cpp' )
	cpp_source( 'sounds_disabled.cpp' )
	cpp_source( 'sounds_disabled_cfg.cpp' )
	cpp_source( 'sounds_disabled_data.cpp' )
	cpp_source( 'sounds_disabled_model.cpp' )
	cpp_source( 'sounds_disabled_to_dialog.cpp' )
	cpp_source( 'sounds_disabled_view.cpp' )
	cpp_source( 'sounds_played_model.cpp' )
	cpp_source( 'sounds_played_view.cpp' )
	cpp_source( 'source_manual_dialog.cpp' )
	cpp_source( 'sources.cpp' )
	cpp_source( 'sources_dialog.cpp' )
	cpp_source( 'sources_mainwindow.cpp' )
	cpp_source( 'sources_mainwindow_cfg.cpp' )
	cpp_source( 'sources_model.cpp' )
	cpp_source( 'sources_widget.cpp' )
	cpp_source( 'sources_widget_view.cpp' )
	cpp_source( 'tool_window.cpp' )
	cpp_source( 'tool_window_object.cpp' )
	cpp_source( 'utils.cpp' )
	cpp_source( 'window_state_cfg.cpp' )
	cpp_source( 'windows_cfg.cpp' )
	cpp_source( 'with_menu.cpp' )
}
